// Generated by CoffeeScript 1.7.1
(function() {
  var answer, language, languageArray, languagePresent, languages, _i, _j, _k, _len, _len1, _len2;

  languagePresent = false;

  languages = {
    Gaelic: {
      name: "Gaelic",
      spokenBy: "leperchuans"
    },
    Klingon: {
      name: "Klingon",
      spokenBy: "worf"
    },
    French: {
      name: "french",
      spokenBy: "bagquet eaters"
    },
    afrikkans: {
      name: "afrikkans",
      spokenBy: "people in south africa"
    },
    elvish: {
      name: "elvish",
      spokenBy: "people with pointy ears"
    },
    swiss: {
      name: "swiss",
      spokenBy: "netural people"
    },
    userLanguage: {
      name: "userlanguage",
      spokenBy: "spokenBy"
    }
  };

  languageArray = [languages.Gaelic, languages.Klingon, languages.French, languages.afrikkans, languages.elvish, languages.swiss];

  for (_i = 0, _len = languageArray.length; _i < _len; _i++) {
    language = languageArray[_i];
    console.log(language.name + " spokenby: " + language.spokenBy);
  }

  while (answer !== "quit") {
    console.log(languagePresent);
    if (languagePresent === true) {
      break;
    }
    answer = prompt("please add a language, quit to stop");
    if (answer === "quit") {
      break;
    }
    for (_j = 0, _len1 = languageArray.length; _j < _len1; _j++) {
      language = languageArray[_j];
      if (language.name === answer) {
        languagePresent = true;
        alert("we do not need this language to be added");
        break;
      }
    }
    if (languagePresent === false) {
      languages.userLanguage.name = answer;
      alert("language added");
      languages.userLanguage.spokenBy = prompt("please also teach me who this is spokenby");
      languageArray[languageArray.length] = languages.userLanguage;
      break;
    }
  }

  for (_k = 0, _len2 = languageArray.length; _k < _len2; _k++) {
    language = languageArray[_k];
    console.log(language.name + " spokenby: " + language.spokenBy);
  }

}).call(this);

//# sourceMappingURL=if.map
