// Generated by CoffeeScript 1.7.1
(function() {
  var i;

  i = 1;

  while (i < 10) {
    i = i + 1;
    console.log("Chase!");
  }

  console.log("Goodbye Mr.Chase");

  console.log("I refuse to go");

}).call(this);
