// Generated by CoffeeScript 1.7.1
(function() {
  var count, languagename, languages, languagesarray, yesNo, yesno, _i, _ref;

  languages = {
    swahili: {
      name: "swahili",
      continent: "africa",
      number: 28
    },
    french: {
      name: "french",
      continent: "europe",
      number: 26
    },
    esperanto: {
      name: "esperanto",
      continent: "world",
      number: 4
    },
    dutch: {
      name: "dutch",
      continent: "europe",
      number: 54
    },
    Afrikaans: {
      name: "afrikaans",
      continent: "africa",
      number: 34
    },
    Gaelic: {
      name: "Gaelic",
      continent: "europe",
      number: 34
    }
  };

  count = 0;

  languagesarray = [languages.swahili, languages.french, languages.esperanto, languages.dutch, languages.Afrikaans, languages.Gaelic];

  for (_i = 0, _ref = languagesarray.length; 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--) {
    console.log(languagesarray[count].name, "number of letters", languagesarray[count].number, "continent:", languagesarray[count].continent);
    count = count + 1;
  }

  yesNo = prompt("do you want to add a language? Y or N");

  if (yesno = "Y") {
    languagename = prompt("languagename");
    languages.New.name = languagename;
  } else {

  }

}).call(this);
